### ISSUE TITLE
SSLError: hostname 'webdav.yandex.ru' doesn't match 'webdav-beta.yandex.ru'

### ISSUE THREAD

**Issue by francoislaurent** [francoislaurent/escale#22]
The following error happens from time to time on startup:
```
CRITICAL[*]:manager.run: Traceback (most recent call last):
  File "*/manager/manager.py", line 153, in run
    self.sanityCheck()
  File "*/manager/manager.py", line 217, in sanityCheck
    for lock in self.relay.listCorrupted(self.dir):
  File "*/relay/relay.py", line 468, in listCorrupted
    ls = self._safe(self._list, remote_dir, recursive=recursive, stats=['mtime'])
  File "*/relay/relay.py", line 427, in _safe
    raise e
SSLError: hostname 'webdav.yandex.ru' doesn't match 'webdav-beta.yandex.ru'
```

**Comment by francoislaurent** [comment]
I have never observed this service-specific error again since I reported it.
