### ISSUE TITLE
type error with rclone backend

### ISSUE THREAD

**Issue by francoislaurent** [francoislaurent/escale#33]
```
15/01 04:07 escale.*@yandex[DEBUG]  manager.run:362 Traceback (most recent call last):
  File "escale/manager/manager.py", line 310, in run
    new |= self.upload()
  File "escale/manager/index.py", line 303, in upload
    self.relay.setUpdateData(page, final_file)
  File "escale/relay/index.py", line 922, in setUpdateData
    self.base_relay._push(data, self.updateData(page, mode='w'))
  File "escale/relay/generic/rclone.py", line 189, in _push
    output=True)
  File "escale/base/subprocess.py", line 84, in with_subprocess
    p = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by francoislaurent** [comment]
This is actually an encryption error:
```
Traceback (most recent call last):
  File "escale/encryption/encryption.py", line 83, in encrypt
    _c = self._encrypt(fi.read())
  File "escale/encryption/fernet.py", line 28, in _encrypt
    return self.cipher.encrypt(data)
  File "~/.local/lib/python3.7/site-packages/cryptography/fernet.py", line 52, in encrypt
    return self._encrypt_from_parts(data, current_time, iv)
  File "~/.local/lib/python3.7/site-packages/cryptography/fernet.py", line 62, in _encrypt_from_parts
    ciphertext = encryptor.update(padded_data) + encryptor.finalize()
  File "~/.local/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "~/.local/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "~/.local/lib/python3.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data), len(data)
OverflowError: integer 5469348304 does not fit '32-bit int'
```
